apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecomonorepo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ecomonorepo
  template:
    metadata:
      labels:
        app: ecomonorepo
    spec:
      containers:
        - name: ecomonorepo
          image: hftamayo/ecommerce_monorepo:0.1.1
          ports:
            - containerPort: 8012
            - containerPort: 5173
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: DATABASE_URL
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: POSTGRES_DB
            - name: POSTGRES_HOST
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: POSTGRES_HOST
            - name: POSTGRES_PORT
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: POSTGRES_PORT
            - name: DATALAYER_NAME
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: DATALAYER_NAME
            - name: DATA_STRUCTURE
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: DATA_STRUCTURE
            - name: EXEC_MODE
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: EXEC_MODE
            - name: SEED_DEVELOPMENT
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: SEED_DEVELOPMENT
            - name: SEED_PRODUCTION
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: SEED_PRODUCTION
            - name: FRONTEND_ORIGINS
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: FRONTEND_ORIGINS
            - name: VITE_BACKEND_URL
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: VITE_BACKEND_URL
            - name: VITE_APP_NAME
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: VITE_APP_NAME                  