apiVersion: batch/v1
kind: Job
metadata:
  name: pgecommerce-migration-job
spec:
  template:
    spec:
      containers:
        - name: ecomonorepo-migration
          image: hftamayo/ecommerce_monorepo:0.1.1
          command: ["sh", "-c", "cd apps/server && npx prisma migrate deploy && npx prisma generate"]
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: DATABASE_URL
      restartPolicy: OnFailure