apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgecommerce
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pgecommerce
  template:
    metadata:
      labels:
        app: pgecommerce
    spec:
      containers:
        - name: pgecommerce
          image: hftamayo/pgecommerce:0.0.1
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: POSTGRES_DB