FROM postgres:14-alpine

RUN apk add --no-cache bash

WORKDIR /docker-entrypoint-initdb.d

COPY db.sql .

EXPOSE 5432

CMD ["docker-entrypoint.sh", "postgres"]

#to run this file:
#docker build -f Dockerfile.db -t your-image-name .
#docker run --env-file .env your-image-name
#docker build -f Dockerfile.db -t hftamayo/pgecommerce:0.0.1 .
#docker network create ecommerce_network
#the bellow commands need to be run on the root of the project
#docker run --name pgecommerce --network ecommerce_network -p 5432:5432 -d --env-file .env hftamayo/pgecommerce:0.0.1
#docker run --name pgecommerce -p 5432:5432 -d --env-file .env hftamayo/pgecommerce:0.0.1
